AllCops:
  Exclude:
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - 'bin/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
